# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhrL2MRuLziv-thqOpQgK_fzbaNSM5tO
"""

# importing Numpy package
import numpy as np
import math as m

x=60
y=45
z=30
# creating a 2X2 Numpy matrix
n_array = np.array([[np.cos(x*np.pi/180), np.sin(x*np.pi/180),1],[np.cos(y*np.pi/180), np.sin(y*np.pi/180),1],[np.cos(z*np.pi/180), np.sin(z*np.pi/180),1] ])

# Displaying the Matrix
print(" Matrix is:")
print(n_array)

# calculating the determinant of matrix
det =np.linalg.det(n_array)
newdet=det*det
print("\nDeterminant of given 3X3 matrix:")
print(float(det))

print(float(newdet))

i=np.array([[np.cos(y*np.pi/180), np.sin(y*np.pi/180)],[np.cos(z*np.pi/180), np.sin(z*np.pi/180)] ])
c1=np.linalg.det(i)
j=np.array([[np.cos(x*np.pi/180), np.sin(x*np.pi/180)],[np.cos(z*np.pi/180), np.sin(z*np.pi/180)] ])
c2=np.linalg.det(j)
k=np.array([[np.cos(x*np.pi/180), np.sin(x*np.pi/180)],[np.cos(y*np.pi/180), np.sin(y*np.pi/180)] ])
c3=np.linalg.det(k)
print(c1)
print(c2)
print(c3)

answer= newdet/(2*c1*c2*c3)
print(answer)













